"""
LaTeX Resume Builder -- FastAPI server
Serves the website, compiles LaTeX server-side, and calls a local AI model
(Ollama by default; switch to vLLM by setting USE_VLLM=true).

Each browser session gets its own working directory under temp/sessions/,
so multiple users are fully isolated. The pdflatex runs in a thread pool so
AI calls and compile jobs can overlap without blocking each other.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import subprocess
import threading
import time
import uuid
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

import httpx
from fastapi import Cookie, FastAPI, Request, Response
from fastapi.responses import FileResponse, JSONResponse

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR      = Path(__file__).parent.parent
TEMPLATES_DIR = BASE_DIR / "templates"
TEMP_DIR      = BASE_DIR / "temp"
INDEX_PATH    = BASE_DIR / "index.html"
SESSIONS_DIR  = TEMP_DIR / "sessions"
MODEL_FILE    = TEMP_DIR / "model.txt"
METRICS_FILE  = TEMP_DIR / "metrics.json"
TESTS_DIR     = BASE_DIR / "tests"

SESSIONS_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Config -- override any of these with environment variables
# ---------------------------------------------------------------------------
OLLAMA_URL    = os.getenv("OLLAMA_URL",   "http://localhost:11434")
DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:3b")

# Set USE_VLLM=true and LLM_BASE_URL=http://localhost:8001 (wherever vLLM
# is listening) to switch inference from Ollama to vLLM with no other changes.
USE_VLLM     = os.getenv("USE_VLLM", "").lower() in ("1", "true", "yes")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", OLLAMA_URL)

# MiKTeX / TeX Live path detection.  shutil.which() covers anything on PATH;
# the candidate list handles common Windows installs where MiKTeX is not on PATH.
def _find_pdflatex() -> str:
    on_path = shutil.which("pdflatex")
    if on_path:
        return on_path
    _candidates = [
        # System-wide MiKTeX (default installer target)
        r"C:\Program Files\MiKTeX\miktex\bin\x64\pdflatex.exe",
        r"C:\Program Files (x86)\MiKTeX\miktex\bin\x64\pdflatex.exe",
        # Per-user MiKTeX (default per-user installer target for any user)
        str(Path.home() / r"AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe"),
    ]
    for c in _candidates:
        if Path(c).exists():
            return c
    # Nothing found — return the system-wide path so the error message is helpful.
    return _candidates[0]

PDFLATEX = _find_pdflatex()

# Set DEV=1 to skip index.html caching so edits are served without restart.
DEV_MODE = os.getenv("DEV", "").lower() in ("1", "true", "yes")

MAX_COMPILES = 2   # concurrent pdflatex processes
MAX_SOURCE_BYTES = 500_000   # 500 KB -- guard against runaway source uploads
MAX_IMAGE_BYTES  = 8_000_000 # ~6 MB image (base64) — enough for a scanned page

# Session lifetime: how long a session can sit idle before it is deleted.
# Override with SESSION_MAX_AGE env var (seconds).  Default = 24 h.
SESSION_MAX_AGE      = int(os.getenv("SESSION_MAX_AGE", str(86400)))
SESSION_CLEANUP_INTERVAL = 3600   # run the janitor once per hour

# ---------------------------------------------------------------------------
# In-process rate limiter (sliding-window, keyed by client IP)
# Works on any OS; complements the nginx limit_req layer.
#
# Limits (per IP, per 60-second window):
#   chat    — 10  (AI + compile; one every ~6 s is comfortable)
#   compile — 20  (template/source/reset; compile-only)
#   api     — 60  (lightweight reads)
# ---------------------------------------------------------------------------
_rl_store: dict[str, list[float]] = defaultdict(list)
_rl_lock: asyncio.Lock          # initialised inside lifespan() on the running loop

# ---------------------------------------------------------------------------
# Global AI performance metrics — stored per model.
# Persisted to temp/metrics.json so they survive server restarts.
#
# In-memory structure:  _metrics: dict[model_name, list[entry]]
# On-disk structure:    {"qwen2.5-coder:3b": [...], "phi4": [...], ...}
#
# Each entry records (see _record_metric for full field list):
#   ts              Unix timestamp of the request (seconds)
#   model           Ollama model name used
#   mode            Interaction mode: "resume", "math", or "image"
#   elapsed_ms      Total wall-clock time for the full request (AI + compile)
#   prompt_tokens   Token count of the prompt sent to the model
#   gen_tokens      Token count generated by the model in the response
#   tokens_per_sec  Model generation speed (gen_tokens / AI time)
#   edit_ok         Whether the SEARCH/REPLACE edit was applied (resume mode)
#   compile_ok      Whether pdflatex compiled without error (null = not attempted)
#
# Cap: _METRICS_CAP entries per model (oldest dropped when exceeded).
# ---------------------------------------------------------------------------
_METRICS_CAP  = 1000                          # max entries stored per model
_metrics: dict[str, list[dict]] = {}          # keyed by model name
_metrics_lock = threading.Lock()              # guards both the dict and file writes


def _load_metrics() -> dict[str, list[dict]]:
    """Read persisted metrics from disk at startup.

    Handles two formats:
    - New  (dict)  — {model: [entries, ...]}  written by this version.
    - Legacy (list) — flat list written by earlier versions; auto-migrated
      by bucketing each entry on its "model" field.

    Returns {} on any error.
    """
    try:
        if METRICS_FILE.exists():
            data = json.loads(METRICS_FILE.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                # New per-model format — enforce cap on each bucket.
                return {
                    model: bucket[-_METRICS_CAP:]
                    for model, bucket in data.items()
                    if isinstance(bucket, list)
                }
            elif isinstance(data, list):
                # Legacy flat list — migrate by grouping on model name.
                print("  INFO metrics: migrating legacy flat list to per-model format.")
                bucketed: dict[str, list[dict]] = {}
                for entry in data:
                    m = entry.get("model", "unknown") if isinstance(entry, dict) else "unknown"
                    bucketed.setdefault(m, []).append(entry)
                return {
                    model: bucket[-_METRICS_CAP:]
                    for model, bucket in bucketed.items()
                }
    except Exception as exc:
        print(f"  WARN metrics load: {exc}")
    return {}


def _save_metrics_locked() -> None:
    """Write _metrics to disk atomically. Caller must hold _metrics_lock.

    Writes to a .tmp file first, then renames over the real file so a
    crash or Ctrl+C mid-write never leaves a corrupted metrics.json.
    """
    try:
        tmp = METRICS_FILE.with_suffix(".tmp")
        tmp.write_text(
            json.dumps(_metrics, separators=(",", ":")),
            encoding="utf-8",
        )
        os.replace(tmp, METRICS_FILE)   # atomic on POSIX; near-atomic on Windows
    except Exception as exc:
        print(f"  WARN metrics save: {exc}")


def _record_metric(entry: dict) -> None:
    """Append entry to the per-model bucket, enforcing the per-model cap."""
    model = entry.get("model", "unknown")
    with _metrics_lock:
        bucket = _metrics.setdefault(model, [])
        bucket.append(entry)
        if len(bucket) > _METRICS_CAP:
            _metrics[model] = bucket[-_METRICS_CAP:]
        _save_metrics_locked()

# ---------------------------------------------------------------------------
# Model catalog + installed-model cache
#
# _MODEL_CATALOG  — every model the app supports, grouped by family/mode.
#                   Shown in the dropdown whether installed or not.
# _model_cache    — {"installed": set[str], "running": bool}
#                   Populated once at startup by querying Ollama; refreshed
#                   on every /api/models call so newly-pulled models appear
#                   without a server restart.
# ---------------------------------------------------------------------------
_MODEL_CATALOG = [
    # ── Qwen2.5-Coder ────────────────────────────────────────────────────────
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:0.5b",  "mode": "text"},
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:1.5b",  "mode": "text"},
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:3b",    "mode": "text"},
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:7b",    "mode": "text"},
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:14b",   "mode": "text"},
    {"family": "Qwen2.5-Coder", "name": "qwen2.5-coder:32b",   "mode": "text"},
    # ── Microsoft Phi-4 ──────────────────────────────────────────────────────
    {"family": "Phi-4",         "name": "phi4-mini",            "mode": "text"},
    {"family": "Phi-4",         "name": "phi4",                 "mode": "text"},
    # ── Mistral ──────────────────────────────────────────────────────────────
    {"family": "Mistral",       "name": "mistral",              "mode": "text"},
    {"family": "Mistral",       "name": "mistral-small",        "mode": "text"},
    # ── DeepSeek-R1 ──────────────────────────────────────────────────────────
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:1.5b",    "mode": "text"},
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:7b",      "mode": "text"},
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:8b",      "mode": "text"},
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:14b",     "mode": "text"},
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:32b",     "mode": "text"},
    {"family": "DeepSeek-R1",   "name": "deepseek-r1:70b",     "mode": "text"},
    # ── Meta Llama ───────────────────────────────────────────────────────────
    {"family": "Meta Llama",    "name": "llama3.3",             "mode": "text"},
    # ── Meta CodeLlama ───────────────────────────────────────────────────────
    {"family": "CodeLlama",     "name": "codellama:7b",         "mode": "text"},
    {"family": "CodeLlama",     "name": "codellama:13b",        "mode": "text"},
    {"family": "CodeLlama",     "name": "codellama:34b",        "mode": "text"},
    # ── Vision / OCR (image-to-LaTeX mode) ───────────────────────────────────
    {"family": "Vision / OCR",  "name": "moondream",            "mode": "vision"},
    {"family": "Vision / OCR",  "name": "llava-phi3",           "mode": "vision"},
    {"family": "Vision / OCR",  "name": "llava",                "mode": "vision"},
    {"family": "Vision / OCR",  "name": "llava:13b",            "mode": "vision"},
    {"family": "Vision / OCR",  "name": "minicpm-v",            "mode": "vision"},
]

_model_cache: dict = {"installed": set(), "running": False}

_RL_WINDOW  = 60.0   # sliding window width in seconds
_RL_CHAT    = 10
_RL_COMPILE = 20
_RL_API     = 60


async def _rate_limit(request: Request, max_requests: int) -> bool:
    """
    Returns True if the request is within the limit, False if it should be
    rejected. Uses a per-(IP, limit-tier) sliding window stored in memory,
    so hitting the API read limit never blocks the chat or compile limits.
    """
    global _rl_store
    ip  = (request.client.host if request.client else "unknown")
    key = f"{ip}:{max_requests}"   # different tiers get separate buckets
    now = time.monotonic()
    cutoff = now - _RL_WINDOW

    async with _rl_lock:
        # Bound memory: when the store exceeds 10 000 unique IP+tier pairs
        # (e.g. an IP-rotation flood), rebuild it keeping only keys that still
        # have at least one timestamp inside the current window.
        if len(_rl_store) > 10_000:
            _rl_store = defaultdict(list, {
                k: v for k, v in _rl_store.items()
                if any(t > cutoff for t in v)
            })
        times = _rl_store[key]
        # Evict timestamps outside the current window
        _rl_store[key] = [t for t in times if t > cutoff]
        if len(_rl_store[key]) >= max_requests:
            return False
        _rl_store[key].append(now)
    return True


def _too_many() -> JSONResponse:
    return JSONResponse(
        {"error": "Too many requests — please wait a moment and try again."},
        status_code=429,
    )


# ---------------------------------------------------------------------------
# Session cleanup -- background task, runs every SESSION_CLEANUP_INTERVAL s
# ---------------------------------------------------------------------------
async def _cleanup_sessions() -> None:
    """
    Delete session directories whose files haven't been touched in
    SESSION_MAX_AGE seconds.  Uses the newest file-mtime inside the
    directory as the "last active" timestamp, so an in-progress compile
    (which writes .aux / .log / .pdf) is never mistakenly deleted.
    """
    while True:
        await asyncio.sleep(SESSION_CLEANUP_INTERVAL)
        cutoff  = time.time() - SESSION_MAX_AGE
        removed = 0
        errors  = 0
        try:
            for d in SESSIONS_DIR.iterdir():
                if not (d.is_dir() and _UUID_RE.match(d.name)):
                    continue
                try:
                    files = [f for f in d.iterdir() if f.is_file()]
                    last_active = (
                        max(f.stat().st_mtime for f in files)
                        if files else d.stat().st_mtime
                    )
                    if last_active < cutoff:
                        shutil.rmtree(d, ignore_errors=True)
                        removed += 1
                except Exception as exc:
                    errors += 1
                    print(f"  WARN cleanup [{d.name[:8]}]: {exc}")
        except Exception as exc:
            print(f"  WARN cleanup scan failed: {exc}")
        if removed or errors:
            print(f"  cleanup: removed {removed} expired session(s)"
                  + (f", {errors} error(s)" if errors else ""))


# FIX #10: separate connect vs. read timeouts.
# connect=5 s means a firewalled (non-refused) host surfaces an error in 5 s
# instead of hanging for 10 full minutes.
_LLM_TIMEOUT = httpx.Timeout(connect=5.0, read=600.0, write=60.0, pool=60.0)

# FIX #3: only accept well-formed UUID4 session IDs from cookies.
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)

# ---------------------------------------------------------------------------
# App lifecycle  (FIX #1 + #2: uses lifespan instead of the deprecated on_event hooks)
# ---------------------------------------------------------------------------
_sem:  asyncio.Semaphore               # created inside the running event loop
_pool = ThreadPoolExecutor(max_workers=MAX_COMPILES, thread_name_prefix="latex")
_index_html: bytes = b""              # cached at startup (skipped when DEV=1)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── startup ──────────────────────────────────────────────────────────────
    global _sem, _index_html, _rl_lock, _metrics, _model_cache
    _sem     = asyncio.Semaphore(MAX_COMPILES)
    _rl_lock = asyncio.Lock()   # must be created on the running event loop
    _metrics = _load_metrics()  # restore persisted metrics from temp/metrics.json
    total_loaded = sum(len(b) for b in _metrics.values())
    print(f"  Metrics   : {total_loaded} entries across {len(_metrics)} model(s) loaded from disk")
    # If the file was in the legacy flat-list format, _load_metrics() migrated it
    # in memory but didn't rewrite the file.  Flush now so the disk is always in
    # the current per-model dict format after startup.
    with _metrics_lock:
        _save_metrics_locked()
    if not DEV_MODE:
        _index_html = INDEX_PATH.read_bytes()   # cache once; re-read per-req in DEV mode
    # Query Ollama once at startup to find which catalog models are installed.
    # /api/models serves from this cache; the cache is also refreshed on every
    # /api/models call so newly-pulled models appear without a restart.
    try:
        async with httpx.AsyncClient(
            timeout=httpx.Timeout(connect=4, read=6, write=4, pool=4)
        ) as client:
            r = await client.get(f"{OLLAMA_URL}/api/tags")
            r.raise_for_status()
            raw = [m["name"] for m in r.json().get("models", [])]
            # Accept both "phi4" and "phi4:latest" as matching a catalog entry "phi4".
            inst: set[str] = set(raw)
            for name in raw:
                if name.endswith(":latest"):
                    inst.add(name[:-7])
            _model_cache["installed"] = inst
            _model_cache["running"]   = True
        n_inst = sum(1 for m in _MODEL_CATALOG if m["name"] in _model_cache["installed"])
        print(f"  Models    : {n_inst}/{len(_MODEL_CATALOG)} catalog models installed")
    except Exception:
        print(f"  Models    : Ollama not reachable at startup — will retry on first /api/models call")
    print(f"  pdflatex  : {PDFLATEX}")
    print(f"  LLM URL   : {LLM_BASE_URL}  ({'vLLM' if USE_VLLM else 'Ollama'})")
    print(f"  Model     : {_active_model()}")
    print(f"  Sessions  : {SESSIONS_DIR}")
    ttl_h = SESSION_MAX_AGE // 3600
    print(f"  Session TTL: {ttl_h} h  (cleanup every {SESSION_CLEANUP_INTERVAL // 60} min)")

    # Start session janitor as a background asyncio task.
    # It sleeps first, so it never runs during startup.
    _cleanup_task = asyncio.create_task(_cleanup_sessions(), name="session-cleanup")

    yield

    # ── shutdown ─────────────────────────────────────────────────────────────
    _cleanup_task.cancel()
    try:
        await _cleanup_task
    except asyncio.CancelledError:
        pass
    # FIX #14: clean up the thread pool so pdflatex workers aren't left dangling.
    _pool.shutdown(wait=False)


app = FastAPI(lifespan=lifespan)


# ---------------------------------------------------------------------------
# Active model (shared across all sessions, persisted in temp/model.txt)
# ---------------------------------------------------------------------------
_active_model_cache: str | None = None   # avoids a disk read on every LLM call

def _active_model() -> str:
    global _active_model_cache
    if _active_model_cache:
        return _active_model_cache
    if MODEL_FILE.exists():
        m = MODEL_FILE.read_text(encoding="utf-8").strip()
        if m:
            _active_model_cache = m
            return m
    return DEFAULT_MODEL


_model_lock = threading.Lock()

def _set_model(name: str) -> None:
    global _active_model_cache
    # Lock guards against concurrent writes from two simultaneous model-switch requests.
    with _model_lock:
        name = name.strip()
        MODEL_FILE.write_text(name, encoding="utf-8")
        _active_model_cache = name   # keep cache in sync


# ---------------------------------------------------------------------------
# Sessions -- each browser gets a UUID stored in a cookie
# ---------------------------------------------------------------------------
def _valid_sid(session_id: Optional[str]) -> bool:
    """FIX #3: reject any cookie value that isn't a well-formed UUID4."""
    return bool(session_id and _UUID_RE.match(session_id))


def _sd(sid: str) -> Path:
    d = SESSIONS_DIR / sid
    d.mkdir(parents=True, exist_ok=True)
    return d

def _tex(sid: str)  -> Path: return _sd(sid) / "working.tex"
def _pdf(sid: str)  -> Path: return _sd(sid) / "working.pdf"
def _log(sid: str)  -> Path: return _sd(sid) / "working.log"
def _last(sid: str) -> Path: return _sd(sid) / "last_good.tex"
def _cur(sid: str)  -> Path: return _sd(sid) / "current.txt"


def _resolve(session_id: Optional[str]) -> tuple[str, bool]:
    """Return (sid, is_new). Generates a fresh UUID when session is absent or invalid."""
    # FIX #3: validate UUID format before trusting the value as a filesystem path.
    if _valid_sid(session_id) and (SESSIONS_DIR / session_id).exists():  # type: ignore[arg-type]
        return session_id, False  # type: ignore[return-value]
    return str(uuid.uuid4()), True


def _set_cookie(resp: Response | JSONResponse, sid: str, is_new: bool) -> None:
    if is_new:
        # Align cookie lifetime with the server-side session TTL (+ 1 h grace).
        # Previously 30 days, which outlived the 24-hour session by 29× and
        # caused stale cookies pointing at deleted session directories.
        resp.set_cookie("session_id", sid, max_age=SESSION_MAX_AGE + 3600,
                        samesite="lax", httponly=True)


def _init_session(sid: str) -> None:
    """Copy the default template into a fresh session if working.tex is missing."""
    if not _tex(sid).exists():
        names = _tnames()
        tmpl  = _cur_tmpl(sid, names)
        if tmpl:
            try:
                shutil.copy2(TEMPLATES_DIR / f"{tmpl}.tex", _tex(sid))
            except FileNotFoundError:
                pass   # template deleted between listing and copy; session starts empty


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
def _tnames() -> list[str]:
    if not TEMPLATES_DIR.exists():
        return []
    return sorted(p.stem for p in TEMPLATES_DIR.glob("*.tex"))


def _tlabel(name: str) -> str:
    p = TEMPLATES_DIR / f"{name}.tex"
    if p.exists():
        first = p.read_text(encoding="utf-8").split("\n", 1)[0]
        m = re.match(r"^%\s*!TEMPLATE:\s*(.+?)\s*$", first)
        if m:
            return m.group(1)
    return name


def _cur_tmpl(sid: str, names: list[str] | None = None) -> str:
    if names is None:
        names = _tnames()
    cf = _cur(sid)
    if cf.exists():
        c = cf.read_text(encoding="utf-8").strip()
        if c in names:
            return c
    if "classic" in names:
        return "classic"
    return names[0] if names else ""


def _load_tmpl(sid: str, name: str) -> bool:
    if name not in _tnames():
        return False
    try:
        shutil.copy2(TEMPLATES_DIR / f"{name}.tex", _tex(sid))
    except FileNotFoundError:
        return False   # template deleted between listing and copy
    _cur(sid).write_text(name, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# LaTeX compilation
# ---------------------------------------------------------------------------
def _compile_sync(sid: str) -> dict:
    """Blocking; always runs in the thread pool via _compile()."""
    d   = _sd(sid)
    tex = _tex(sid)
    pdf = _pdf(sid)
    log = _log(sid)

    # FIX (High): block \input / \include pointing to external paths before
    # handing the source to pdflatex (-no-shell-escape blocks \write18 / RCE
    # but does not prevent file-read via \input{C:\...}).
    try:
        latex_src = tex.read_text(encoding="utf-8", errors="ignore")
        guard_err = _guard_latex(latex_src)
        if guard_err:
            return {"ok": False, "error": guard_err}
    except OSError as exc:
        return {"ok": False, "error": f"Cannot read source file: {exc}"}

    try:
        result = subprocess.run(
            [PDFLATEX,
             "-interaction=nonstopmode",
             "-halt-on-error",
             # Sandboxing: disable \write18 so LaTeX source cannot execute
             # arbitrary shell commands, even if a user crafts malicious input.
             "-no-shell-escape",
             f"-output-directory={d}", str(tex)],
            capture_output=True, cwd=str(d),
            # 45 s was too short for first MiKTeX run (font-cache rebuild
            # + on-demand package downloads can take 90-120 s).
            timeout=120,
        )
    except subprocess.TimeoutExpired:
        return {"ok": False,
                "error": "Compilation timed out (120 s). A LaTeX package may be downloading -- try again."}
    except FileNotFoundError:
        # FIX (Low): don't leak the full install path in the API response.
        return {"ok": False, "error": "pdflatex not found. Check your MiKTeX installation."}

    log_text = log.read_text(encoding="utf-8", errors="ignore") if log.exists() else ""

    if pdf.exists() and "Output written on" in log_text:
        shutil.copy2(tex, _last(sid))
        return {"ok": True, "error": None}

    # FIX (Medium): use the return code as a fallback when the log is empty
    # (e.g. pdflatex crashed without writing anything).
    lines = log_text.splitlines()
    hits  = [l for l in lines if l.startswith("!") or re.match(r"^l\.\d+", l)]
    if hits:
        err = "\n".join(hits[:8])
    elif lines:
        err = "\n".join(lines[-12:])
    elif result.returncode != 0:
        err = f"pdflatex exited with code {result.returncode} and wrote no log."
    else:
        err = "Unknown compilation error."
    return {"ok": False, "error": err}


async def _compile(sid: str) -> dict:
    # FIX #1: get_running_loop() is the correct call inside an async context.
    # get_event_loop() is deprecated in Python 3.10+ and raises in future versions.
    loop = asyncio.get_running_loop()
    async with _sem:
        return await loop.run_in_executor(_pool, _compile_sync, sid)


async def _revert(sid: str) -> None:
    """Restore last_good.tex and recompile. Logs if the revert itself fails."""
    lg = _last(sid)
    if lg.exists():
        shutil.copy2(lg, _tex(sid))
        rv = await _compile(sid)
        if not rv["ok"]:
            print(f"  WARN [{sid[:8]}]: revert compile failed: {rv['error']}")


# ---------------------------------------------------------------------------
# Edit parsing + application
# ---------------------------------------------------------------------------
_EDIT_RX = re.compile(
    r"<{5,}\s*SEARCH[^\n]*\n(.*?)\n={5,}[^\n]*\n(.*?)\n>{5,}\s*REPLACE",
    re.DOTALL | re.IGNORECASE,   # accept lowercase search/replace from some models
)


def _parse(text: str) -> dict:
    # Build match list once; reuse for both edits and leading-text extraction.
    matches = list(_EDIT_RX.finditer(text))
    # Strip leading/trailing blank lines from each captured group.
    # Models (especially Phi-4) sometimes add an extra blank line inside the
    # marker fences; stripping it here prevents false "not found" failures.
    edits   = [{"search": m.group(1).strip("\n"),
                 "replace": m.group(2).strip("\n")} for m in matches]
    msg     = text[: matches[0].start()].strip() if matches else text.strip()
    return {"message": msg or "Done.", "edits": edits}


def _apply(content: str, edits: list) -> dict:
    c = content.replace("\r", "")
    for e in edits:
        s = e["search"].replace("\r", "")
        r = e["replace"].replace("\r", "")
        # Reject empty OR whitespace-only SEARCH text. A blank "   " is truthy
        # but would match the first run of spaces in the document and corrupt it.
        if not s.strip():
            return {"ok": False, "content": content, "error": "Empty SEARCH block."}

        # ── Primary: exact match ──────────────────────────────────────────
        if s in c:
            c = c.replace(s, r, 1)
            continue

        # ── Fallback: trailing-whitespace-normalised match ───────────────
        # Models often copy the snippet correctly but strip trailing spaces
        # or add a stray blank line, making exact match fail even though the
        # intent is unambiguous.  Normalise both sides (rstrip each line),
        # check for a line-boundary match, then splice at the line level so
        # the rest of the document is untouched.
        had_trailing_nl = c.endswith("\n")
        c_lines = c.splitlines()
        s_norm  = "\n".join(ln.rstrip() for ln in s.splitlines())
        c_norm  = "\n".join(ln.rstrip() for ln in c_lines)
        idx     = c_norm.find(s_norm) if s_norm else -1
        if idx != -1:
            # Accept only when the match starts AND ends on a line boundary, so
            # a short search can't splice out the middle or tail of a longer line
            # (e.g. "\section{Intro}" must not match "\section{Introduction}").
            end          = idx + len(s_norm)
            starts_clean = idx == 0 or c_norm[idx - 1] == "\n"
            ends_clean   = end == len(c_norm) or c_norm[end] == "\n"
            if starts_clean and ends_clean:
                line_start = c_norm[:idx].count("\n")
                line_count = s_norm.count("\n") + 1
                c = "\n".join(
                    c_lines[:line_start]
                    + r.splitlines()
                    + c_lines[line_start + line_count:]
                )
                # Restore the trailing newline this working copy had before the
                # splice (splitlines/join drops it). Anchor on `c`, not the
                # original `content`, so earlier edits' changes are respected.
                if had_trailing_nl and not c.endswith("\n"):
                    c += "\n"
                continue

        return {"ok": False, "content": content,
                "error": f"SEARCH text not found:\n{s}"}
    return {"ok": True, "content": c, "error": None}


# ---------------------------------------------------------------------------
# LLM client -- Ollama now; set USE_VLLM=true + LLM_BASE_URL to switch
# Returns (content, perf_dict | None).  perf_dict contains Ollama's native
# timing and token stats; it is None when using vLLM (not exposed there).
# ---------------------------------------------------------------------------
async def _llm(system: str, messages: list,
               images: list[str] | None = None) -> tuple[str, dict | None]:
    """Call the active model.  images is a list of base64-encoded image strings
    (for vision models); they are attached to the last user message."""
    model = _active_model()
    msgs  = [{"role": "system", "content": system}] + messages

    # Attach images to the last user message when provided
    if images and msgs and msgs[-1].get("role") == "user":
        msgs[-1] = {**msgs[-1], "images": images}

    # Use a larger context window for image-to-LaTeX tasks so the model can
    # output a complete document without being cut off.
    num_ctx = 16384 if images else 8192

    # FIX #10: separate connect vs. read timeout.
    async with httpx.AsyncClient(timeout=_LLM_TIMEOUT) as client:
        if USE_VLLM:
            # vLLM exposes the OpenAI-compatible endpoint
            r = await client.post(f"{LLM_BASE_URL}/v1/chat/completions", json={
                "model": model, "messages": msgs,
                "temperature": 0.1, "stream": False,
            })
        else:
            # Ollama native endpoint (supports num_ctx for context window)
            r = await client.post(f"{OLLAMA_URL}/api/chat", json={
                "model": model, "messages": msgs, "stream": False,
                "options": {"temperature": 0.1, "num_ctx": num_ctx},
            })
        r.raise_for_status()
        data = r.json()
        content = (data["choices"][0]["message"]["content"] if USE_VLLM
                   else data["message"]["content"])

        # Extract Ollama's native performance counters from the response body.
        # These are only present on the Ollama path (stream:false returns them
        # in the single response object).  vLLM does not expose them.
        perf: dict | None = None
        if not USE_VLLM:
            eval_dur_ns  = data.get("eval_duration") or 0
            total_dur_ns = data.get("total_duration") or 0
            gen_tok      = data.get("eval_count") or 0
            perf = {
                "model":         data.get("model", model),
                "prompt_tokens": data.get("prompt_eval_count") or 0,
                "gen_tokens":    gen_tok,
                "total_ms":      round(total_dur_ns / 1_000_000),
                "tokens_per_sec": (round(gen_tok / (eval_dur_ns / 1e9), 1)
                                   if eval_dur_ns > 0 else 0),
            }
        return content, perf


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------
_CHAT_SYS = """\
You edit a LaTeX document by making small, targeted text replacements.

When the user asks for a change, reply with ONE short sentence then one or more edit blocks:

<<<<<<< SEARCH
snippet copied verbatim from the current file
=======
the replacement snippet
>>>>>>> REPLACE

Always include ALL THREE marker lines AND the SEARCH snippet.
The SEARCH block must be copied CHARACTER-FOR-CHARACTER from the file —
preserve every space, backslash, brace, and line break exactly as they appear.
Do NOT rephrase, reformat, add blank lines, or change indentation.
Include 2-3 lines of context so the snippet is unique in the file.

Worked example. User: "change the section title to Methods". The file contains:
\\section{{Introduction}}
Your reply:
Changed the section title to Methods.
<<<<<<< SEARCH
\\section{{Introduction}}
=======
\\section{{Methods}}
>>>>>>> REPLACE

Rules:
- Produce valid LaTeX; escape special chars (& % $ # _) in inserted text.
- Do NOT output the whole file, do NOT use code fences.
- If no change is requested, reply in plain text with NO edit blocks.
- SEARCH text must match the file exactly — even one wrong space will fail.

Current document.tex:
{document}"""

# Prompt used when the user uploads an image and wants it recreated as LaTeX.
# No SEARCH/REPLACE — the model outputs the whole document from scratch.
_CREATE_SYS = """\
You are a LaTeX expert. Recreate the document shown in the image as a complete, compilable LaTeX source file.

Rules:
- Output ONLY raw LaTeX, starting with \\documentclass and ending with \\end{{document}}.
- Do NOT wrap in markdown code fences (no ``` or ```latex).
- Do NOT add any explanation, commentary, or preamble text before \\documentclass.
- Reproduce the layout, structure, fonts, and content as faithfully as possible.
- Use only standard packages (geometry, fontenc, inputenc, amsmath, graphicx, etc.).
- The document must compile cleanly with pdflatex -no-shell-escape."""

_FIX_SYS = """\
Fix the LaTeX compile error below using SEARCH/REPLACE blocks only. Do not output the whole file.

<<<<<<< SEARCH
verbatim text from the file
=======
corrected text
>>>>>>> REPLACE

document.tex:
{document}

pdflatex error:
{error}"""

# Prompt used when mode=="math": generate a complete step-by-step solution document.
# The model outputs the whole LaTeX file (no SEARCH/REPLACE).
_MATH_SYS = """\
You are a mathematics tutor and LaTeX expert.

The user will give you a math problem to solve, or ask you to extend/refine an existing solution.
Output a COMPLETE, compilable LaTeX document containing the full step-by-step working.

Document structure:
1. Problem statement in bold at the top
2. Step-by-step solution — number every step, explain each one in plain English
3. Use align or align* for multi-line equation chains
4. Final answer clearly boxed with \\boxed{{}}

LaTeX requirements — use exactly these packages:
\\documentclass[12pt,a4paper]{{article}}
\\usepackage[margin=2.5cm]{{geometry}}
\\usepackage[T1]{{fontenc}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{amsmath,amssymb,amsthm}}
\\usepackage{{parskip}}

Rules:
- Output ONLY raw LaTeX, starting with \\documentclass and ending with \\end{{document}}.
- Do NOT wrap in markdown code fences.
- Do NOT add any text before \\documentclass.
- If the user refines or extends, output the FULL updated document.

Current document (context for refinements — empty on first problem):
{document}"""

# ---------------------------------------------------------------------------
# Security helpers
# ---------------------------------------------------------------------------

# FIX (High): validate model names before writing to disk.
# Accepts only the characters Ollama uses in its own naming scheme.
_MODEL_NAME_RX = re.compile(r'^[a-zA-Z0-9:._\-]{1,200}$')

# FIX (High): block LaTeX \input / \include pointing to absolute paths or
# path-traversal sequences. -no-shell-escape already blocks \write18 (RCE);
# this closes the remaining file-disclosure vector.
_GUARD_LATEX_RX = re.compile(
    r'\\(?:input|include|openin)\b\s*(?:\d+\s*=\s*)?\{([^}]*)\}',
    re.IGNORECASE,
)
# Matches the no-brace form used by plain TeX: \input filename
# (space-separated, no curly braces).  Standard pdflatex supports this too.
_GUARD_LATEX_RX2 = re.compile(
    r'\\input\b\s+([^\s{%\\][^\s{%]*)',
    re.IGNORECASE,
)

_PATH_SUSPICIOUS = re.compile(r'^[A-Za-z]:[/\\]')

def _path_is_external(path: str) -> bool:
    return ('..' in path
            or path.startswith('/')
            or path.startswith('\\')
            or bool(_PATH_SUSPICIOUS.match(path)))

def _guard_latex(latex: str) -> str | None:
    """Return an error string if the source contains suspicious file-access
    directives, or None if safe to compile."""
    for m in _GUARD_LATEX_RX.finditer(latex):
        path = m.group(1).strip()
        if _path_is_external(path):
            return (f"Blocked: LaTeX directive references an external path "
                    f"('{path}'). Only relative includes within the document "
                    f"directory are allowed.")
    # Also check the no-brace plain-TeX form: \input filename
    for m in _GUARD_LATEX_RX2.finditer(latex):
        path = m.group(1).strip()
        if _path_is_external(path):
            return (f"Blocked: \\input references an external path "
                    f"('{path}'). Only relative includes are allowed.")
    return None


# Strips ```latex ... ``` or ``` ... ``` fences that vision models sometimes add.
_FENCE_RX = re.compile(r"^```[a-zA-Z]*\n(.*?)\n```\s*$", re.DOTALL)

def _strip_fences(text: str) -> str:
    m = _FENCE_RX.match(text.strip())
    return m.group(1).strip() if m else text.strip()


def _extract_latex(text: str) -> str:
    """Extract just the LaTeX document from \documentclass to \end{document}.

    Models frequently prefix their output with prose ('Certainly! Here is...')
    or suffix it with commentary.  Slicing to the known document boundaries
    prevents pdflatex seeing 'C' as line 1 and failing with
    'Missing \\begin{document}'.
    """
    start = text.find("\\documentclass")
    end   = text.rfind("\\end{document}")
    if start != -1 and end != -1:
        return text[start : end + len("\\end{document}")].strip()
    return text.strip()


# ---------------------------------------------------------------------------
# Helper: build a JSONResponse and attach a session cookie when needed
# ---------------------------------------------------------------------------
def _resp(data: dict, sid: str, is_new: bool, status: int = 200) -> JSONResponse:
    r = JSONResponse(content=data, status_code=status)
    _set_cookie(r, sid, is_new)
    return r


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/")
async def root(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_API): return _too_many()
    sid, is_new = _resolve(session_id)
    _init_session(sid)
    if is_new or not _pdf(sid).exists():
        await _compile(sid)          # ensure PDF is ready before returning HTML
    # DEV=1 reads the file fresh each request so edits appear without restart.
    html = INDEX_PATH.read_bytes() if DEV_MODE else _index_html
    resp = Response(html, media_type="text/html; charset=utf-8")
    _set_cookie(resp, sid, is_new)
    return resp


@app.get("/api/pdf")
async def get_pdf(request: Request, download: str = "", session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_API): return _too_many()
    # FIX #3: validate UUID before using it as a path component.
    if not _valid_sid(session_id) or not _pdf(session_id).exists():  # type: ignore[arg-type]
        return Response(status_code=404, content="No PDF yet.")
    headers = {"Cache-Control": "no-store"}
    if download:
        headers["Content-Disposition"] = 'attachment; filename="resume.pdf"'
    return FileResponse(str(_pdf(session_id)), media_type="application/pdf",  # type: ignore[arg-type]
                        headers=headers)


@app.get("/api/source")
async def get_source(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_API): return _too_many()
    # FIX #3: validate UUID.
    tex = _tex(session_id) if _valid_sid(session_id) else None  # type: ignore[arg-type]
    content = tex.read_text(encoding="utf-8") if tex and tex.exists() else ""
    return JSONResponse({"content": content})


@app.post("/api/source")
async def post_source(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_COMPILE): return _too_many()
    if not _valid_sid(session_id):
        return JSONResponse({"ok": False, "error": "No session."}, status_code=400)
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"ok": False, "error": "Invalid JSON body."}, status_code=400)
    content = body.get("content", "")
    # FIX #13: reject runaway payloads before writing to disk.
    if len(content.encode("utf-8")) > MAX_SOURCE_BYTES:
        return JSONResponse({"ok": False,
                             "error": f"Source too large (max {MAX_SOURCE_BYTES // 1000} KB)."})
    _tex(session_id).write_text(content, encoding="utf-8")  # type: ignore[arg-type]
    c = await _compile(session_id)  # type: ignore[arg-type]
    if not c["ok"]:
        await _revert(session_id)  # type: ignore[arg-type]
    # "reverted" tells the frontend to re-fetch the source so the textarea
    # reflects the last-good file that was restored, not the bad content.
    return JSONResponse({"ok": c["ok"], "error": c["error"], "reverted": not c["ok"]})


@app.post("/api/reset")
async def reset(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_COMPILE): return _too_many()
    if not _valid_sid(session_id):
        return JSONResponse({"ok": False, "error": "No session."}, status_code=400)
    names = _tnames()
    tmpl  = _cur_tmpl(session_id, names)  # type: ignore[arg-type]
    if tmpl:
        try:
            shutil.copy2(TEMPLATES_DIR / f"{tmpl}.tex", _tex(session_id))  # type: ignore[arg-type]
        except FileNotFoundError:
            return JSONResponse({"ok": False, "error": f"Template '{tmpl}' not found on disk."})
    c = await _compile(session_id)  # type: ignore[arg-type]
    return JSONResponse({"ok": c["ok"], "error": c["error"]})


@app.get("/api/templates")
async def get_templates(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_API): return _too_many()
    names = _tnames()
    return JSONResponse({
        "templates": [{"name": n, "label": _tlabel(n)} for n in names],
        "current":   _cur_tmpl(session_id or "", names) if _valid_sid(session_id) else "",  # type: ignore[arg-type]
    })


@app.post("/api/template")
async def post_template(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_COMPILE): return _too_many()
    sid, is_new = _resolve(session_id)
    try:
        body = await request.json()
    except Exception:
        return _resp({"ok": False, "error": "Invalid JSON body."}, sid, is_new, status=400)
    name = str(body.get("name", ""))
    if not _load_tmpl(sid, name):
        return _resp({"ok": False, "error": f"Unknown template: {name}"}, sid, is_new)
    c = await _compile(sid)
    return _resp({"ok": c["ok"], "error": c["error"]}, sid, is_new)


@app.get("/api/models")
async def get_models(request: Request):
    """Return the full model catalog with installed flags.

    Attempts a live Ollama refresh on each call so newly-pulled models
    appear without a restart. Falls back to the startup-cached installed
    set if Ollama is temporarily unreachable.

    Response shape:
      {
        "models": [
          {"name": "phi4", "family": "Phi-4", "mode": "text", "installed": true},
          {"name": "qwen2.5-coder:32b", "family": "Qwen2.5-Coder", "mode": "text", "installed": false},
          ...
        ],
        "current": "phi4",
        "running": true
      }
    """
    if not await _rate_limit(request, _RL_API): return _too_many()
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(connect=4, read=4, write=4, pool=4)) as client:
            r = await client.get(f"{OLLAMA_URL}/api/tags")
            r.raise_for_status()
            raw = [m["name"] for m in r.json().get("models", [])]
            inst: set[str] = set(raw)
            for name in raw:
                if name.endswith(":latest"):
                    inst.add(name[:-7])
            _model_cache["installed"] = inst
            _model_cache["running"]   = True
    except Exception:
        _model_cache["running"] = False

    models_out = [
        {
            "name":      m["name"],
            "family":    m["family"],
            "mode":      m["mode"],
            "installed": m["name"] in _model_cache["installed"],
        }
        for m in _MODEL_CATALOG
    ]
    return JSONResponse({
        "models":  models_out,
        "current": _active_model(),
        "running": _model_cache["running"],
    })


@app.post("/api/model")
async def post_model(request: Request):
    if not await _rate_limit(request, _RL_API): return _too_many()
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"ok": False, "error": "Invalid JSON body."}, status_code=400)
    name = str(body.get("name", "")).strip()
    if not name:
        return JSONResponse({"ok": False, "error": "No model name provided."})
    # FIX (High): reject names containing characters outside Ollama's naming
    # scheme and cap length to prevent oversized writes to model.txt.
    if not _MODEL_NAME_RX.match(name):
        return JSONResponse({"ok": False, "error": "Invalid model name."})
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(connect=4, read=4, write=4, pool=4)) as client:
            r = await client.get(f"{OLLAMA_URL}/api/tags")
            r.raise_for_status()
            installed = [m["name"] for m in r.json().get("models", [])]
        # Normalize: Ollama stores tag-less pulls as "model:latest".
        # Accept bare names (e.g. "phi4") that match a "phi4:latest" entry.
        installed_norm = set(installed)
        for m in installed:
            if m.endswith(":latest"):
                installed_norm.add(m[: -len(":latest")])
        if name not in installed_norm:
            return JSONResponse({"ok": False,
                                 "error": f"Model '{name}' is not installed. "
                                          f"Run: ollama pull {name}"})
        _set_model(name)
        return JSONResponse({"ok": True, "error": None})
    except Exception:
        return JSONResponse({"ok": False, "error": "Ollama isn't running."})


# ---------------------------------------------------------------------------
# Test-results API
# Scans the tests/ directory for completed test runs (folders that contain
# a results.json) and serves their PDFs for the in-app Test Results panel.
# ---------------------------------------------------------------------------

# Known suites in display order.  Only suites whose directory exists are returned.
_TEST_SUITES = [
    {"id": "math",   "name": "Math Solver",   "subdir": "math"},
    {"id": "resume", "name": "Resume Editor", "subdir": "resume"},
]


@app.get("/api/test-results")
async def get_test_results(request: Request):
    """Return available test-suite runs and their per-problem metadata."""
    if not await _rate_limit(request, _RL_API): return _too_many()

    suites = []
    for spec in _TEST_SUITES:
        suite_dir = TESTS_DIR / spec["subdir"]
        if not suite_dir.is_dir():
            suites.append({**spec, "runs": [], "binder": None})
            continue

        # Collect every sub-folder that contains a results.json.
        runs = []
        for folder in sorted(suite_dir.iterdir()):
            results_file = folder / "results.json"
            if not folder.is_dir() or not results_file.exists():
                continue
            try:
                results = json.loads(results_file.read_text(encoding="utf-8"))
            except Exception:
                continue
            # Build the list of available PDFs so the UI knows which ones exist.
            pdfs = sorted(
                [f.name for f in folder.glob("*.pdf") if f.name[0].isdigit()],
                key=lambda n: int(n.split("_")[0]) if n[0].isdigit() else 999,
            )
            runs.append({
                "folder":  f"{spec['subdir']}/{folder.name}",
                "results": results,
                "pdfs":    pdfs,
            })

        # Check for a pre-built binder PDF at the suite root.
        binder = next(
            (f"{spec['subdir']}/{p.name}" for p in suite_dir.glob("*.pdf") if "Binder" in p.name),
            None,
        )
        suites.append({**spec, "runs": runs, "binder": binder})

    return JSONResponse({"suites": suites})


@app.get("/api/test-pdf")
async def get_test_pdf(request: Request, path: str = ""):
    """Serve a PDF from the tests/ directory.

    The `path` parameter is relative to tests/ (e.g. "math/Math Test/01_Addition.pdf").
    Requests that would escape outside tests/ are rejected with 400.
    """
    if not await _rate_limit(request, _RL_API): return _too_many()
    if not path:
        return Response(status_code=400, content="Missing path parameter.")
    # Resolve and validate: must stay inside TESTS_DIR.
    try:
        target = (TESTS_DIR / path).resolve()
        TESTS_DIR.resolve()   # ensure TESTS_DIR itself resolves cleanly
        target.relative_to(TESTS_DIR.resolve())   # raises ValueError if outside
    except (ValueError, Exception):
        return Response(status_code=400, content="Invalid path.")
    if not target.exists() or not target.is_file() or target.suffix.lower() != ".pdf":
        return Response(status_code=404, content="PDF not found.")
    return FileResponse(str(target), media_type="application/pdf",
                        headers={"Cache-Control": "no-store"})


@app.get("/api/metrics")
async def get_metrics(request: Request):
    """Return per-model AI performance metrics + cross-model aggregate summary.

    Response shape
    ──────────────
    {
      "entries":  [ ...50 most-recent entries across all models, newest last ],
      "summary":  {
        "total":              int,    # total requests recorded across all models
        "model_count":        int,    # number of distinct models seen
        "compile_rate":       float|null,  # % of compile-attempted requests that succeeded
        "avg_elapsed_ms":     int,    # mean wall-clock time across all models
        "avg_tokens_per_sec": float,  # mean generation speed across all models
        "total_tokens":       int,    # total tokens generated across all models
        "by_model": [                 # sorted by request count descending
          {
            "model":              str,
            "count":              int,
            "stored":             int,   # entries kept on disk (≤ 1000)
            "compile_rate":       float|null,
            "avg_elapsed_ms":     int,
            "avg_tokens_per_sec": float,
            "total_tokens":       int,
            "by_mode": {              # breakdown of request count per mode
              "resume": int, "math": int, "image": int
            },
          }, ...
        ],
      },
    }
    """
    if not await _rate_limit(request, _RL_API): return _too_many()

    with _metrics_lock:
        # Snapshot each per-model bucket to avoid holding the lock during aggregation.
        snapshot: dict[str, list[dict]] = {m: list(b) for m, b in _metrics.items()}

    # Flatten to a single sorted list for cross-model aggregates and recent-entries view.
    all_entries: list[dict] = sorted(
        (e for bucket in snapshot.values() for e in bucket),
        key=lambda e: e.get("ts", 0),
    )

    if not all_entries:
        return JSONResponse({"entries": [], "summary": {}})

    # ── Cross-model aggregate ──────────────────────────────────────────────
    total = len(all_entries)

    attempted    = [e for e in all_entries if e.get("compile_ok") is not None]
    compiled     = [e for e in attempted   if e["compile_ok"] is True]
    compile_rate = round(len(compiled) / len(attempted) * 100, 1) if attempted else None

    elapsed_vals = [e["elapsed_ms"]    for e in all_entries if e.get("elapsed_ms")]
    tok_s_vals   = [e["tokens_per_sec"] for e in all_entries if e.get("tokens_per_sec")]
    avg_elapsed_ms = round(sum(elapsed_vals) / len(elapsed_vals)) if elapsed_vals else 0
    avg_tok_s      = round(sum(tok_s_vals)   / len(tok_s_vals),   1) if tok_s_vals else 0
    total_tokens   = sum(e.get("gen_tokens", 0) for e in all_entries)

    # ── Per-model breakdown ────────────────────────────────────────────────
    by_model = []
    for model_name, bucket in sorted(snapshot.items(),
                                     key=lambda kv: len(kv[1]), reverse=True):
        m_attempted = [e for e in bucket if e.get("compile_ok") is not None]
        m_compiled  = [e for e in m_attempted if e["compile_ok"] is True]
        m_elapsed   = [e["elapsed_ms"]     for e in bucket if e.get("elapsed_ms")]
        m_tok_s     = [e["tokens_per_sec"] for e in bucket if e.get("tokens_per_sec")]
        m_modes: dict[str, int] = {"resume": 0, "math": 0, "image": 0}
        for e in bucket:
            md = e.get("mode", "resume")
            if md in m_modes:
                m_modes[md] += 1

        by_model.append({
            "model":              model_name,
            "count":              len(bucket),
            "stored":             len(bucket),   # same as count; explicit for clarity
            "compile_rate":       (round(len(m_compiled) / len(m_attempted) * 100, 1)
                                   if m_attempted else None),
            "avg_elapsed_ms":     round(sum(m_elapsed) / len(m_elapsed)) if m_elapsed else 0,
            "avg_tokens_per_sec": round(sum(m_tok_s)   / len(m_tok_s),   1) if m_tok_s else 0,
            "total_tokens":       sum(e.get("gen_tokens", 0) for e in bucket),
            "by_mode":            m_modes,
        })

    summary = {
        "total":              total,
        "model_count":        len(snapshot),
        "compile_rate":       compile_rate,
        "avg_elapsed_ms":     avg_elapsed_ms,
        "avg_tokens_per_sec": avg_tok_s,
        "total_tokens":       total_tokens,
        "by_model":           by_model,
    }
    # Return the 50 most-recent entries globally (already sorted by ts ascending).
    return JSONResponse({"entries": all_entries[-50:], "summary": summary})


@app.post("/api/chat")
async def chat(request: Request, session_id: Optional[str] = Cookie(None)):
    if not await _rate_limit(request, _RL_CHAT): return _too_many()
    sid, is_new = _resolve(session_id)
    _init_session(sid)

    t0: float = time.monotonic()
    llm_perf: dict | None = None

    try:
        body = await request.json()
    except Exception:
        return _resp({"message": "", "updated": False,
                      "error": "Invalid JSON body."}, sid, is_new, status=400)
    raw_messages = body.get("messages", [])
    if not isinstance(raw_messages, list):
        return _resp({"message": "", "updated": False,
                      "error": "messages must be a list."}, sid, is_new, status=400)
    messages = raw_messages[-20:]
    images   = body.get("images") or []
    if not isinstance(images, list):
        images = []
    mode = body.get("mode", "resume")
    if mode not in ("resume", "math", "image"):
        mode = "resume"                          # unknown modes fall back to edit

    # Guard against oversized image payloads
    total_img_bytes = sum(len(b) for b in images)
    if total_img_bytes > MAX_IMAGE_BYTES:
        return _resp(
            {"message": "", "updated": False,
             "error": f"Image too large ({total_img_bytes // 1_000_000} MB). Max ~6 MB."},
            sid, is_new, status=400,
        )

    tex      = _tex(sid)
    document = tex.read_text(encoding="utf-8") if tex.exists() else ""

    # ── inline helper: record metric + build response ─────────────────────
    def _finish(data: dict, *, edit_ok: bool, compile_ok: bool | None) -> JSONResponse:
        elapsed_ms = round((time.monotonic() - t0) * 1000)
        entry: dict = {
            "ts":            round(time.time()),
            "model":         (llm_perf or {}).get("model", _active_model()),
            "mode":          mode,
            "elapsed_ms":    elapsed_ms,
            "prompt_tokens": (llm_perf or {}).get("prompt_tokens", 0),
            "gen_tokens":    (llm_perf or {}).get("gen_tokens", 0),
            "tokens_per_sec":(llm_perf or {}).get("tokens_per_sec", 0),
            "edit_ok":       edit_ok,
            "compile_ok":    compile_ok,
        }
        _record_metric(entry)
        perf_out = {
            "elapsed_s":      round(elapsed_ms / 1000, 1),
            "gen_tokens":     entry["gen_tokens"],
            "tokens_per_sec": entry["tokens_per_sec"],
            "compile_ok":     compile_ok,
        }
        return _resp({**data, "perf": perf_out}, sid, is_new)

    # ══════════════════════════════════════════════════════════════════════
    # IMAGE-TO-LaTeX CREATE MODE
    # When images are attached the model generates a complete new document
    # from scratch — no SEARCH/REPLACE, full document output.
    # Note: image presence takes precedence over the mode field.  The frontend
    # always sends mode=="image" when images are attached, but guarding on
    # the image list itself makes the dispatch unambiguous regardless.
    # ══════════════════════════════════════════════════════════════════════
    if images:
        try:
            raw, llm_perf = await _llm(_CREATE_SYS, messages, images=images)
        except Exception:
            return _resp(
                {"message": "", "updated": False,
                 "error": ("Can't reach Ollama. Make sure it's running and the active model "
                           "supports vision (llava, minicpm-v, moondream). "
                           "Try: ollama run llava")},
                sid, is_new, status=500,
            )

        latex = _extract_latex(_strip_fences(raw))

        # Require BOTH markers — missing either means the document won't compile.
        if "\\documentclass" not in latex or "\\begin{document}" not in latex:
            return _finish(
                {"message": ("The model didn't return complete LaTeX. "
                             "Make sure you're using a vision-capable model "
                             "(llava, minicpm-v, moondream) and try again.\n\n"
                             + raw[:500]),
                 "updated": False, "error": None},
                edit_ok=False, compile_ok=None,
            )

        tex.write_text(latex, encoding="utf-8")
        c = await _compile(sid)

        if c["ok"]:
            shutil.copy2(tex, _last(sid))
            return _finish(
                {"message": "Document recreated from image and compiled successfully.", "updated": True, "error": None},
                edit_ok=True, compile_ok=True,
            )
        # Try one auto-fix pass on compile failure
        broken     = tex.read_text(encoding="utf-8")
        fix_system = _FIX_SYS.format(
            document=broken.replace("{", "{{").replace("}", "}}"),
            error=c["error"].replace("{", "{{").replace("}", "}}"),
        )
        try:
            fr, _ = await _llm(fix_system,
                               [{"role": "user", "content": "Fix the compile error."}])
            fp = _parse(fr)
            if fp["edits"]:
                fa = _apply(broken, fp["edits"])
                if fa["ok"]:
                    tex.write_text(fa["content"], encoding="utf-8")
                    c = await _compile(sid)
                    if c["ok"]:
                        shutil.copy2(tex, _last(sid))
                        return _finish(
                            {"message": "Document recreated from image (with auto-fix) and compiled.", "updated": True, "error": None},
                            edit_ok=True, compile_ok=True,
                        )
        except Exception:
            pass
        await _revert(sid)
        return _finish(
            {"message": (f"Generated LaTeX from image but it wouldn't compile. "
                         f"Try a different vision model or edit the source manually.\n\n{c['error']}"),
             "updated": False, "error": None},
            edit_ok=True, compile_ok=False,
        )

    # ══════════════════════════════════════════════════════════════════════
    # MATH SOLVER MODE
    # Generates a complete step-by-step LaTeX solution document from scratch
    # (or refines the existing one on follow-up messages).
    # ══════════════════════════════════════════════════════════════════════
    if mode == "math":
        # Bootstrap: when there's no document yet, seed the context with the
        # math template so the model has a complete compilable skeleton to
        # reference.  This prevents "Missing \begin{document}" errors that
        # occur when the model anchors on an empty context and omits the
        # LaTeX preamble.
        math_doc = document.strip()
        if not math_doc:
            tmpl_path = TEMPLATES_DIR / "math.tex"
            if tmpl_path.exists():
                math_doc = tmpl_path.read_text(encoding="utf-8")

        # Escape { and } in the document so Python's str.format() doesn't
        # mistake LaTeX braces (e.g. \frac{a}{b}) for format placeholders.
        math_system = _MATH_SYS.format(
            document=math_doc.replace("{", "{{").replace("}", "}}")
        )
        try:
            raw, llm_perf = await _llm(math_system, messages)
        except Exception:
            model = _active_model()
            return _resp(
                {"message": "", "updated": False,
                 "error": f"Can't reach Ollama. Is it running? Try: ollama run {model}"},
                sid, is_new, status=500,
            )

        latex = _extract_latex(_strip_fences(raw))

        # Require BOTH markers — a document missing either will fail to compile.
        # Previously used `and` so a response with \documentclass but no
        # \begin{document} would silently pass and produce a pdflatex error.
        if "\\documentclass" not in latex or "\\begin{document}" not in latex:
            return _finish(
                {"message": ("The model returned an incomplete LaTeX document. "
                             "Try rephrasing the problem or switching to a "
                             "different model.\n\n" + latex[:400]),
                 "updated": False, "error": None},
                edit_ok=False, compile_ok=None,
            )

        tex.write_text(latex, encoding="utf-8")
        c = await _compile(sid)

        if c["ok"]:
            shutil.copy2(tex, _last(sid))
            return _finish(
                {"message": "Solution compiled.", "updated": True, "error": None},
                edit_ok=True, compile_ok=True,
            )

        # One auto-fix attempt on compile failure
        broken     = tex.read_text(encoding="utf-8")
        fix_system = _FIX_SYS.format(
            document=broken.replace("{", "{{").replace("}", "}}"),
            error=c["error"].replace("{", "{{").replace("}", "}}"),
        )
        try:
            fr, _ = await _llm(fix_system,
                               [{"role": "user", "content": "Fix the compile error."}])
            fp = _parse(fr)
            if fp["edits"]:
                fa = _apply(broken, fp["edits"])
                if fa["ok"]:
                    tex.write_text(fa["content"], encoding="utf-8")
                    c = await _compile(sid)
                    if c["ok"]:
                        shutil.copy2(tex, _last(sid))
                        return _finish(
                            {"message": "Solution compiled (with auto-fix).", "updated": True, "error": None},
                            edit_ok=True, compile_ok=True,
                        )
        except Exception:
            pass

        await _revert(sid)
        return _finish(
            {"message": f"Generated solution but it wouldn't compile. "
                        f"Try rephrasing the problem or switching to a different model.\n\n{c['error']}",
             "updated": False, "error": None},
            edit_ok=True, compile_ok=False,
        )

    # ══════════════════════════════════════════════════════════════════════
    # STANDARD EDIT MODE  (SEARCH/REPLACE)
    # ══════════════════════════════════════════════════════════════════════
    # Escape LaTeX braces before format() so \frac{a}{b} doesn't cause KeyError.
    system = _CHAT_SYS.format(document=document.replace("{", "{{").replace("}", "}}"))

    try:
        reply, llm_perf = await _llm(system, messages)
    except Exception:
        model = _active_model()
        return _resp(
            {"message": "", "updated": False,
             "error": f"Can't reach Ollama. Is it running? Try: ollama run {model}"},
            sid, is_new, status=500,
        )

    parsed = _parse(reply)

    if not parsed["edits"]:
        return _finish(
            {"message": parsed["message"], "updated": False, "error": None},
            edit_ok=False, compile_ok=None,
        )

    # Apply edits; one corrective retry when SEARCH text isn't found
    applied = _apply(document, parsed["edits"])
    if not applied["ok"]:
        try:
            retry = messages + [
                {"role": "assistant", "content": reply},
                {"role": "user",
                 "content": "Your SEARCH text was not found verbatim in the document. "
                            "Open document.tex above and copy the lines "
                            "character-for-character — every space, backslash, and brace "
                            "must match exactly. Include 2-3 surrounding lines for context. "
                            "Do NOT paraphrase or change any whitespace."},
            ]
            r2, _ = await _llm(system, retry)
            p2 = _parse(r2)
            if p2["edits"]:
                a2 = _apply(document, p2["edits"])
                if a2["ok"]:
                    applied, parsed = a2, p2
                else:
                    # Retry still couldn't locate the text; surface its message
                    # (not the first attempt's) in the failure response below.
                    parsed = p2
        except Exception:
            pass

    if not applied["ok"]:
        return _finish(
            {"message": f"{parsed['message']}\n\n"
                        "[!] Couldn't locate the text to change. Try rephrasing.",
             "updated": False, "error": None},
            edit_ok=False, compile_ok=None,
        )

    # Write + compile; one AI repair attempt on compile failure
    tex.write_text(applied["content"], encoding="utf-8")
    c = await _compile(sid)

    if not c["ok"]:
        broken     = tex.read_text(encoding="utf-8")
        fix_system = _FIX_SYS.format(
            document=broken.replace("{", "{{").replace("}", "}}"),
            error=c["error"].replace("{", "{{").replace("}", "}}"),
        )
        try:
            fr, _ = await _llm(fix_system,
                               [{"role": "user", "content": "Fix the compile error."}])
            fp = _parse(fr)
            if fp["edits"]:
                fa = _apply(broken, fp["edits"])
                if fa["ok"]:
                    tex.write_text(fa["content"], encoding="utf-8")
                    c = await _compile(sid)
        except Exception:
            pass

    if not c["ok"]:
        await _revert(sid)
        msg = (f"{parsed['message']}\n\n"
               f"[!] That change wouldn't compile, so I kept the previous version.\n"
               f"{c['error']}")
        return _finish({"message": msg, "updated": False, "error": None},
                       edit_ok=True, compile_ok=False)

    return _finish({"message": parsed["message"], "updated": True, "error": None},
                   edit_ok=True, compile_ok=True)
